config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :fights do
    member do
      put "like",    to: "fights#upvote"
      put "dislike", to: "fights#downvote"
    end
    resources :comments
  end
  get 'home/index'
  devise_for :users, :controllers => {registrations: 'registrations'}
  root to: 'home#index'
  
  #root to: "home#index"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :fight
end

app/models/fight.rb
class Fight < ApplicationRecord
  acts_as_votable
  belongs_to :challenger,
             :class_name => 'User',
             :foreign_key  => "challenger_id"
  belongs_to :challenged,
             :class_name => "User",
             :foreign_key  => "challenged_id"

  has_many :comments
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :username,:firstname, :lastname, presence: true
  validates :username, length: { :within=> 3..10}
  validates :firstname, :lastname, length: {:within => 3..10}

  has_many :fights
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  def create
    @fight = Fight.find(params[:fight_id])
    @comment = @fight.comments.new(comment_params)
    @comment.user = current_user

      respond_to do |format|
        if @comment.save
          format.html { redirect_to @fight, notice: 'Comment was successfully created.' }
          format.json { render json: @comment, status: :created, location: @comment }
        else
          format.html { render :new }
          format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:fight_id, :body, :user_id)
    end
end

app/controllers/fights_controller.rb
class FightsController < ApplicationController
  before_action :set_fight, only: [:show, :edit, :update, :destroy]

  # GET /fights
  # GET /fights.json
  def index
    @fights = Fight.all
  end

  # GET /fights/1
  # GET /fights/1.json
  def show
  end

  # GET /fights/new
  def new
    @fight = Fight.new
  end

  # GET /fights/1/edit
  def edit
  end

  # POST /fights
  # POST /fights.json
  def create
    @fight = Fight.new(fight_params)

    respond_to do |format|
      if @fight.save
        format.html { redirect_to @fight, notice: 'Fight was successfully created.' }
        format.json { render :show, status: :created, location: @fight }
      else
        format.html { render :new }
        format.json { render json: @fight.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fights/1
  # PATCH/PUT /fights/1.json
  def update
    respond_to do |format|
      if @fight.update(fight_params)
        format.html { redirect_to @fight, notice: 'Fight was successfully updated.' }
        format.json { render :show, status: :ok, location: @fight }
      else
        format.html { render :edit }
        format.json { render json: @fight.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fights/1
  # DELETE /fights/1.json
  def destroy
    @fight.destroy
    respond_to do |format|
      format.html { redirect_to fights_url, notice: 'Fight was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

def upvote
  @fight = Fight.find(params[:id])
  @fight.upvote_by current_user
  redirect_to "/fights/#{@fight.id}"
end


def downvote
  @fight = Fight.find(params[:id])
  @fight.downvote_by current_user
  redirect_to "/fights/#{@fight.id}"
end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fight
      @fight = Fight.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fight_params
      params.require(:fight).permit(:schedule, :challenger_id, :challenged_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    def sign_up_params

        params.require(:user).permit(:email, :password, :password_confirmation, :username, :firstname, :lastname)
        
    end
    

end

app/helpers/application_helper.rb
module ApplicationHelper
    def flash_class(level)
      case level
          when 'notice' then "alert alert-dismissable alert-info"
          when 'success' then "alert alert-dismissable alert-success"
          when 'error' then "alert alert-dismissable alert-danger"
          when 'alert' then "alert alert-dismissable alert-danger"
      end
    end
  end
  

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/fights_helper.rb
module FightsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/comments/_comment.html.erb
<div>
    <div class="comments_wrapper clearfix">
        <div class="pull-left">
            <p class="lead"><%= comment.body %></p>
            <p><small>Submitted <strong><%= time_ago_in_words(comment.created_at) %> ago</strong> by
                <%= comment.user.username %></small></p>
        </div>
    </div>
</div>

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :fight_id %>
    <%= form.number_field :fight_id %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Fight</th>
      <th>Body</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.fight_id %></td>
        <td><%= comment.body %></td>
        <td><%= comment.user_id %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fight:</strong>
  <%= @comment.fight_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user_id %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/fights/_form.html.erb
<%= form_with(model: fight, local: true) do |form| %>
  <% if fight.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fight.errors.count, "error") %> prohibited this fight from being saved:</h2>

      <ul>
        <% fight.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :schedule %>
    <%= form.datetime_select :schedule %>
  </div>

    <div class = "control-group">
  <%= form.label :challenger, class: 'control-group'%>
    <div class="controls" >
  <%= collection_select(:fight, :challenger_id, User.all, :id, :username, {}, {:multiple => false}) %>
    </div>
  </div>
  

    <div class = "control-group">
  <%= form.label :challenged, class: 'control-group'%>
    <div class="controls" >
  <%= collection_select(:fight, :challenged_id, User.all, :id, :username, {}, {:multiple => false}) %>
    </div>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/fights/edit.html.erb
<body class="bgs">
<h1>Editing Fight</h1>

<%= render 'form', fight: @fight %>

<%= link_to 'Show', @fight %> |
<%= link_to 'Back', fights_path %>
</body>

app/views/fights/index.html.erb
<!DOCTYPE html>
<html>

<body class="bgf">
    <div style="margin-top: 1em">
<div class="box-inside center-block text-center">

<h1 style="color:red">Resolver no Braço</h1>
<p id="notice"><%= notice %></p>

<table class="table">
  <thead>
    <tr>
      <th>Schedule</th>
      <th>Challenger</th>
      <th>Challenged</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fights.each do |fight| %>
      <tr>
        <td><%= fight.schedule %></td>
        <td><%= fight.challenger.username %></td>
        <td><%= fight.challenged.username %></td>
        
        <td><%= link_to 'SHOW', fight, class:"btn btn-primary" %></td>
        <% if fight.challenger == current_user || fight.challenged == current_user || current_user.admin %>
        <td><%= link_to 'EDIT', edit_fight_path(fight), class:"btn btn-secondary" %></td>
        <td><%= link_to 'DESTROY', fight, method: :delete, data: { confirm: 'Are you sure?' } , class:"btn btn-danger"%></td>
        <% end %>
      </tr>


    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fight', new_fight_path , class:"btn btn-danger btn-lg", style:"color:white; font-weight: bold; text-transform: uppercase;"%>
</div>
</div>
</body>
</html>

app/views/fights/new.html.erb
<body class="bgs">

<h1>New Fight</h1>
<hr>
<%= render 'form', fight: @fight %>

<%= link_to 'Back', fights_path %>
</body>

app/views/fights/show.html.erb
<body class="bgs ">
<div class="container justify-content: center">
<p>
  <strong>Schedule:</strong>
  <%= @fight.schedule %>
</p>

<p>
  <strong>Challenger:</strong>
  <%= @fight.challenger.username %>
</p>

<p>
  <strong>Challenged:</strong>
  <%= @fight.challenged.username %>
</p>
<hr>
</div>

<div class="container justify-content: center">

    <div class="btn-group">

      <%= link_to like_fight_path(@fight), method: :put, class: "btn btn-default" do %>
      <span class="glyphicon glyphicon-chevron-up"></span>
      Challenger Win
      <%= @fight.get_upvotes.size %>
      <% end %>
        
      <%= link_to dislike_fight_path(@fight), method: :put, class: "btn btn-default" do %>
      <span class="glyphicon glyphicon-chevron-up"></span>
      Challenged Win
      <%= @fight.get_downvotes.size %>
      <% end %>
        
      
      <hr>
    </div>
    <div class="col-sm-3 col-xs-offset-6">
      <% if @fight.challenger == current_user || @fight.challenged == current_user %>
      <%= link_to 'EDIT', edit_fight_path(@fight), class:"btn btn-primary", style:"font-weight: bold" %>
      <% end %>
      <%= link_to 'BACK', fights_path, class:"btn btn-warning", style:"font-weight: bold" %>
    </div>
  
  <div class="size col-sm-3 col-xs-offset-6">
  <hr>
  <h2 class="comments_title">
    <%= @fight.comments.count %> Comments
  </h2>

  <div id="comments">
    <%= render :partial => @fight.comments %>
  </div>
  <%= simple_form_for [@fight, Comment.new] do |f| %>
    <div class="field">
      <%= f.text_area :body, class: "form-control" %>
    </div>
    <br>
    <%= f.submit "ADD COMMENT", class:"btn btn-primary", style:"font-weight: bold" %>
  <% end %>
  </div>
  </body>

app/views/home/index.html.erb
<body class="bgh">
    
<body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FightClubFGA</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<body>


    <nav class="navbar navbar-expand-lg">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Alterna navegação">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="container-fluid">
          <div class="navbar-header" ><%= link_to 'FIGHT CLUB', root_path , style:"color:red; font-weight: bold; text-transform: uppercase;"%></div>
          <div class="navbar-right">
           <ul class="nav navbar-nav">
              <li class="nav-link"><%= link_to 'Fights', fights_path  %></li>
              <% if user_signed_in? %>
                <li class="nav-link"><%= link_to 'Account', edit_user_registration_path %></li>
                <li class="nav-link"><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
              <% else %>
                <li class="nav-link"><%= link_to 'Sign up', new_user_registration_path %></li>
                <li class="nav-link"><%= link_to 'Sign in', new_user_session_path %></li>
              <%end%>
            </ul>
        </div>
      </div>
    </nav>
    

    <% flash.each do |name, msg| %>
    <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
    
    <% end %>
    <div style="height: 100%;">
    <%= yield %>
    </div>
  </body>
</html>